### ISSUE TITLE
division by zero error in Crosscat when there are no models is confusing

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#386] opened 2016-03-24 17:43 UTC
Everywhere this might happen, we should report a more comprehensible error message.

**Comment by BelhalK** [comment] 2016-03-24 17:54
Agreed. 
People could think their dataset contains zero and/or missing values (which is not an issue for crosscat) whereas the actual issue is that there generator is empty (no models)

**Comment by fsaad** [comment] 2017-11-13 21:32
Duplicate of https://github.com/probcomp/bayeslite/issues/363

**Closed by fsaad** 2017-11-13 21:32 UTC
