### ISSUE TITLE
OSX build that runs without homebrew python installed

### ISSUE THREAD

**Issue by tibbetts** [probcomp/bayeslite#138] opened 2015-09-14 17:23 UTC
The latest autobuilds fail because homebrew python is not installed on my machine and the test machine. This is a pretty critical issue. Just deleting the captured python doesn't fully work, the python kernels fail to run because they can't find a module:

[I 13:22:44.338 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 13:22:48.497 NotebookApp] Notebook Satellites.ipynb is not trusted
[W 13:22:48.536 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20150914132244 (::1) 28.29ms referer=http://localhost:8889/notebooks/Satellites.ipynb
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named ipykernel
[I 13:22:49.156 NotebookApp] Kernel started: 0e6f702c-82f5-4091-948a-fc378b720996
[I 13:22:52.116 NotebookApp] KernelRestarter: restarting kernel (1/5)
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named ipykernel
[I 13:22:55.124 NotebookApp] KernelRestarter: restarting kernel (2/5)
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named ipykernel
[I 13:22:58.134 NotebookApp] KernelRestarter: restarting kernel (3/5)
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named ipykernel
[W 13:22:59.330 NotebookApp] Timeout waiting for kernel_info reply from 0e6f702c-82f5-4091-948a-fc378b720996

**Comment by gregory-marton** [comment] 2015-11-18 20:35
@raxraxraxraxrax says in flowdoc: 
@tibbetts, do you know in what way you were out of date on Issue #138: OSX build that runs without homebrew python installed by tibbetts in probcomp/bayeslite on GitHub ? Because I’m getting the same error when I try to run Bayeslite on my laptop.

I presume this is with the 0.1.3 build. Interestingly, I never did a homebrew install python on the test machine, except in build@'s account locally (not systemwide), so test@ shouldn't see it.

Interesting, and it's not even the python that build uses:

ssh build@pcg-osx-test.mit.edu
Last login: Wed Nov  4 18:07:04 2015 from 128.30.108.217
PCG-OSX-TEST:~ build$ which python
/usr/bin/python
PCG-OSX-TEST:~ build$ python --version
Python 2.7.10
PCG-OSX-TEST:~ build$ echo $PATH
/Users/build/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin


jenkins@probcomp-4:~$ ssh test@pcg-osx-test.mit.edu
Last login: Wed Nov 18 14:44:03 2015
PCG-OSX-TEST:~ test$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PCG-OSX-TEST:~ test$ which python
/usr/bin/python

**Comment by raxraxraxraxrax** [comment] 2015-11-18 20:39
Macintosh-4:~ raxl$ which python
/usr/bin/python
Macintosh-4:~ raxl$ python --version
Python 2.7.5
Macintosh-4:~ raxl$ echo $PATH
/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

Did "out of date" here mean that we require a Python later than 2.7.5? If so, we might want to think about a good way to point this out to users instead of just having a "Dead kernel" error message in the notebook.

**Comment by gregory-marton** [comment] 2015-11-18 21:01
PYTHONPATH is not getting set by venv/bin/activate, so the libraries just aren't available. Not sure why this is different on osx10.9 vs. osx10.11, which is what the test machine uses.

When I explicitly set the pythonpath, then it works fine, so will simply incorporate that into start.sh, which already knows what it should be set to.

**Comment by tibbetts** [comment] 2015-11-21 14:53
Apologies for being obscure. I'm pretty sure I was out of date in that I hadn't installed the latest .app build.

**Comment by raxraxraxraxrax** [comment] 2015-12-10 20:21
For what it's worth: New laptop, and this still happens on OS X El Capitan 10.11.1 with the 0.1.3 .app build on the website. I am skeptical right now that the .app build on the website will work without intervention for anyone, since I have only heard instances of it not working. :(

**Comment by gregory-marton** [comment] 2015-12-11 10:36
The 0.1.3 build doesn't include the relevant change. I can produce a named
0.1.4rc1 dmg that you can test this with, if you like, or I can help you
find an up-to-date candidate built by jenkins on probcomp-4.csail.mit.edu:
/scratch/dmgs/

Grem


Gregory A. Marton
Cell: 617-858-0775
Calendar: http://csail.mit.edu/~gremio/cal
Plus: http://goo.gl/Ne09o
Web: http://csail.mit.edu/~gremio

**Comment by raxraxraxraxrax** [comment] 2015-12-11 19:37
Confirmed that the most recent 0.1.4 build does not have these issues on OS X 10.11.

**Comment by gregory-marton** [comment] 2015-12-22 20:42
Can we close this and https://github.com/probcomp/bdbcontrib/issues/60 now?

**Comment by gregory-marton** [comment] 2015-12-28 17:30
I think I fixed this. Please reopen if it's still an issue.

**Closed by gregory-marton** 2015-12-28 17:30 UTC
