### ISSUE TITLE
Crosscat insertmany broken?

### ISSUE THREAD

**Issue by axch** [probcomp/bayeslite#123] opened 2015-09-08 19:56 UTC
Taylor tells me that crosscat's implementation of insertmany is likely to be broken, as it does not interact with the crosscat subsample table.

**Comment by gregory-marton** [comment] 2015-11-17 22:31
Duplicate of #30?

**Comment by riastradh-probcomp** [comment] 2015-11-17 23:23
Not exactly -- this is about Crosscat's implementation of the `insertmany` API, whereas #30 is about (re)designing the API and/or using it to implement `INSERT` in BQL.

**Comment by fsaad** [comment] 2017-11-13 22:43
The insert_many function no longer exists as of 5bf3d2d.

Ticket to implement this feature correctly is: https://github.com/probcomp/bayeslite/issues/493

**Closed by fsaad** 2017-11-13 22:43 UTC
