### ISSUE TITLE
error when running check.sh

### ISSUE THREAD

**Issue by yarden** [probcomp/bayeslite#101] opened 2015-08-06 03:21 UTC
Hi all,

I get the error below when running ``check.sh`` in bayeslite. Installation went smoothly. Any thoughts on this? Thanks, Yarden

```
$ ./check.sh
[...snip...]
============================================= test session starts ==============================================
platform darwin -- Python 2.7.8 -- py-1.4.25 -- pytest-2.6.3
collected 348 items 

tests/test_bql.py .....................
tests/test_codebook.py ..
tests/test_core.py ...................x..s..............................xxxxxxxxxxxxxxx..............................................s.sss...sss.sssssss........................ss..ss..ss..ss..ss..ss..ss..ss.sss.sss.sss.sss........................ssss....ssssssssssssssssssssssss.........
tests/test_correlation.py .
tests/test_csv.py .............
tests/test_guess.py ..
tests/test_legacy.py .
tests/test_parse.py ............
tests/test_read_csv.py .
tests/test_stats.py ......
tests/test_subsample.py .
shell/tests/test_pretty.py .x
shell/tests/test_shell.py EEEEEEEEEEEEEEEEEE

==================================================== ERRORS ====================================================
______________________________________ ERROR at setup of test_shell_loads ______________________________________

    @pytest.fixture
    def spawnbdb():
        c = spawnjr('bayeslite --no-init-file --memory')
        c.delaybeforesend = 0
        c.expect_lines([
            'Welcome to the Bayeslite %s shell.' % (bayeslite_version,),
            "Type `.help' for help.",
        ])
>       c.expect_prompt()

shell/tests/test_shell.py:87: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test_shell.spawnjr object at 0x104497250>

    def expect_prompt(self):
        self.expect_exact('bayeslite> ')
>       assert self.before == ''
E       assert '\x1b[?1034h' == ''
E         - \x1b[?1034h

shell/tests/test_shell.py:68: AssertionError
___________________________________ ERROR at setup of test_python_expression ___________________________________

    @pytest.fixture
    def spawnbdb():
        c = spawnjr('bayeslite --no-init-file --memory')
        c.delaybeforesend = 0
        c.expect_lines([
            'Welcome to the Bayeslite %s shell.' % (bayeslite_version,),
            "Type `.help' for help.",
        ])
>       c.expect_prompt()

shell/tests/test_shell.py:87: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test_shell.spawnjr object at 0x104497410>

    def expect_prompt(self):
        self.expect_exact('bayeslite> ')
>       assert self.before == ''
E       assert '\x1b[?1034h' == ''
E         - \x1b[?1034h

shell/tests/test_shell.py:68: AssertionError
_____________________________ ERROR at setup of test_help_returns_list_of_commands _____________________________

    @pytest.fixture
    def spawnbdb():
        c = spawnjr('bayeslite --no-init-file --memory')
        c.delaybeforesend = 0
        c.expect_lines([
            'Welcome to the Bayeslite %s shell.' % (bayeslite_version,),
            "Type `.help' for help.",
        ])
>       c.expect_prompt()

shell/tests/test_shell.py:87: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test_shell.spawnjr object at 0x10452d410>

    def expect_prompt(self):
        self.expect_exact('bayeslite> ')
>       assert self.before == ''
E       assert '\x1b[?1034h' == ''
E         - \x1b[?1034h

shell/tests/test_shell.py:68: AssertionError
______________________________________ ERROR at setup of test_trace_usage ______________________________________

[...snip...]
```

**Comment by tibbetts** [comment] 2015-09-24 16:01
@yarden I recommend you try the new installer, we believe the problem is resolved. Feel free to reopen the issue if you still have a problem.

**Comment by gregory-marton** [comment] 2015-09-24 16:11
That new installer being:
http://probcomp.csail.mit.edu/bayesdb/downloads/Bayeslite-0.1.dmg

**Comment by riastradh-probcomp** [comment] 2015-09-24 16:11
This isn't a terribly important issue, particularly now that the focus has shifted away from the bayeslite shell as a user interface and toward calling the Python API from ipython notebooks.  But the bug in the shell tests is likely still there -- sometimes OS X ptys apparently behave differently in ways that our code doesn't mod out.  So it would be nice to diagnose this and fix it.

Some candidate relevant variables:
- Version of OS X?
- Output of `env` before you run `check.sh`?
- Output of `stty -a` before you run `check.sh`?
- Any noteworthy shell/terminal/python/... customizations on your system?

**Comment by gregory-marton** [comment] 2015-11-17 22:03
Not having heard back from @yarden and being at version 0.1.3, I think it's time to close this.

**Comment by riastradh-probcomp** [comment] 2015-11-17 23:02
I see no evidence that the problem has been fixed, nor am I aware of any changes that might have fixed it.

**Comment by gregory-marton** [comment] 2015-11-18 19:45
@riastradh-probcomp , we have been unable to reproduce the problem, and have no indication that it is not fixed, and we have substantially changed the installation procedure, and have tested it relatively thoroughly. I'm not inclined to track irreproducible issues simply because the reporter hasn't confirmed a fix.

**Closed by gregory-marton** 2015-11-18 19:45 UTC
Labels: waiting
