### ISSUE TITLE
bayeslite check.sh silently does nothing if pytest is not installed and never handles dependencies

### ISSUE THREAD

**Issue by madeleineth** [probcomp/bayeslite#373] opened 2016-02-08 15:54 UTC
check.sh does nothing if pytest is not installed.

On Ubuntu 14.04, if you do:

> git clone git@github.com:probcomp/bayeslite.git bayeslite-fail2
> cd bayeslite-fail2
> virtualenv --system-site-packages venv
> . ./venv/bin/activate
> ./check.sh

`check.sh` exits immediately with no output. If you install `pytest`, it starts running tests, but does not install dependencies, so you eventually get an error like:

> E   ImportError: No module named apsw

**Comment by gregory-marton** [comment] 2016-02-08 16:57
f2e9742 fixes the silent check.sh. It does not address the fact that check.sh makes no attempt to install dependencies. Recommend `python setup.py install` or `python setup.py develop` for that, before using check.sh. Perhaps that needs a documentation fix. Alternately, I think `python setup.py test` will do the appropriate prior installation.

**Comment by gregory-marton** [comment] 2016-02-08 16:58
In particular, we need to update http://probcomp.csail.mit.edu/bayesdb/install.html

**Comment by riastradh-probcomp** [comment] 2016-02-08 18:26
Date: Mon, 08 Feb 2016 09:45:42 -0800
   From: Madeleine Thompson <notifications@github.com>

   check.sh does nothing if pytest is not installed.

   On Ubuntu 14.04, if you do:

   > git clone git@github.com:probcomp/bayeslite.git bayeslite-fail2
   > cd bayeslite-fail2
   > virtualenv --system-site-packages venv
   > . ./venv/bin/activate
   > ./check.sh

   `check.sh` exits immediately with no output.

This is a new bug.  I expect that if you check the exit status, you
will find that it is nonzero.  But it should print a message in that
case.  The problem is this line:

lib_avail=`./pythenv.sh python -m pytest --version 2>&1 | grep 'This is pytest'`

If either subcommand returns nonzero, there will be no output but the
shell script will terminate and return nonzero.

There's another new bug here which is that it uses `python' and not
`"$PYTHON"'.  It should be something like:

lib_avail=`./pythenv.sh "$PYTHON" -m pytest --version 2>&1 | grep 'This is pytest'` || lib_avail=

   If you install `pytest`, it starts running tests, but does not
   install dependencies, so you eventually get an error like:

   > E   ImportError: No module named apsw

This is intentional.  check.sh checks the bayeslite build; it does not
touch your system outside that.

**Comment by gregory-marton** [comment] 2016-02-08 18:37
@riastradh-probcomp the first two are already fixed and explained above. The last, I think, has a different cause. That we get as far as there being no apsw means that we did go get a bunch of other dependencies. I think it's more to do with the fact that python-apsw does not install correctly without some options. @madeleineth try doing

```
pip install --no-cache-dir bayeslite-apsw --install-option="fetch" --install-option="--sqlite" --install-option="--version=3.9.2"
```

before check.sh? I'm not recommending that a solution, just to check if that is indeed the problem.

**Comment by madeleineth** [comment] 2016-02-08 19:22
If I run @gregory-marton's install command, and I have pytest installed, I get:

    shell/tests/test_shell.py:100: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    self = <test_shell.spawnjr object at 0x7f08dd72e290>, cmd = '.csv dha /home/ubuntu/bayeslite-fail2/shell/tests/../../tests/dha.csv'

        def sendexpectcmd(self, cmd):
            self.sendline(cmd)
            self.expect_exact('\r\n')
            # XXX Kludge to skip pty-introduced control characters on line
            # wraps which vary from system to system (e.g., Mac OS X
            # inserts SPC BS at end of line, whereas Linux inserts SPC CR).
            def remove_control(s):
                return s.translate(None, ''.join(map(chr, range(32 + 1) + [127])))
    >       assert remove_control(self.before) == remove_control(cmd)
    E       assert '.csvdha/home...[C[C[C[C[C[Kv' == '.csvdha/home/...tests/dha.csv'
    E         Skipping 56 identical leading characters in diff, use -v to show
    E         - sts/dha.csvM[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Kv
    E         + sts/dha.csv

**Comment by gregory-marton** [comment] 2016-02-08 19:26
That's progress. I think we should close this bug, and open two new ones: one about bayeslite-apsw needing options, and one about the dha.csv thing you just found (because check.sh now patently does indeed do something). @madeleineth would you like to do the honors?

@riastradh-probcomp could you make me an owner on bayelite-apsw on pypi? I'd like to be able to tag and push a version that fixes the above.

**Comment by riastradh-probcomp** [comment] 2016-02-08 19:26
Date: Mon, 8 Feb 2016 18:25:54 +0000
   From: Taylor R Campbell <riastradh+probcomp@csail.mit.edu>

   lib_avail=`./pythenv.sh "$PYTHON" -m pytest --version 2>&1 | grep 'This is pytest'` || lib_avail=

Better yet, the whole thing including the following conditional should
just be:

if ! ./pythenv.sh "$PYTHON" -m pytest --version 2>&1 | grep -q 'This is pytest'
then
    printf >&2 'Unable to find pytest.\n'
    exit 1
fi

**Closed by gregory-marton** 2016-02-08 19:26 UTC

**Comment by riastradh-probcomp** [comment] 2016-02-08 19:33
Apparently Github is broken, because I didn't get any replies to this bug, or notification that it was closed, until I logged in.

I don't understand what the issue with apsw is, but yes, if anything it should be a separate issue.
